version: '3.1'
services:
  contacts:
    build: '.'
    restart: unless-stopped
    container_name: contacts-bot-${DOMAIN}
    env_file:
      .env
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-secure.loadbalancer.server.port=80"
    networks:
      - web
volumes:
  data:
networks:
  web:
    external: true
